from .AB import ABLoss
from .AT import Attention
from .CC import Correlation
from .FitNet import HintLoss
from .FSP import FSP
from .FT import FactorTransfer
from .KD import DistillKL
from .KDSVD import KDSVD
from .NST import NSTLoss
from .PKT import PKT
from .RKD import RKDLoss
from .SP import Similarity
from .VID import VIDLoss
from .TripleT_KD import FADLoss,TDA_KLLoss
from .OFD import OFD
from .ReviewKD import ReviewKD
from .CAT_KD import CAT_KD
from .HDKD import HDKDLoss
from .CRD import CRD
from .AttnFD import AttnKD
from .DKD import DKD
from .NormKD import NormKD

